---
title: "README"
author: "Han-Yu"
date: "07/06/2020"
output: html_document
---

The data set comes from UCI Machine Learning Repository website, http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones. 
The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. 
Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) 
wearing a smartphone (Samsung Galaxy S II) on the waist.

I used subject_train, X_train and Y_train and merged them into one file, 
called train. Within train file, I used descriptive activity names, and named measurments 
as time_frequency_domain according to the original README.txt. The similar procedures were 
applied to subject_test, X_test and Y_testand created a single file called test. 
Then, I mereged train and test into one data set, called train_test, with 10299 observations and 564 variables. 

Next step, I extracted only the measurements on the mean and standard deviation 
for each measurement, and generated two new variables to represent each mean and 
standard deviation of the row. At this point, train_test has 10299 obervations and 566 variables.

Finally, from train_test, I created a second, independent tidy data set with 
the average of each variable for each activity and each subject, called tidy_data. 
